apiVersion: apps/v1
kind: Deployment
metadata:
  name: httpdoges
  namespace: httpdoges
spec:
  replicas: 2
  selector:
    matchLabels:
      app: httpdoges
  template:
    metadata:
      labels:
        app: httpdoges
    spec:
      containers:
      - name: nginx
        image: ghcr.io/shibe/httpdoges:dummy
        imagePullPolicy: Always
        ports:
        - containerPort: 80
        resources:
          requests:
            memory: "64Mi"
            cpu: "50m"
          limits:
            memory: "128Mi"
            cpu: "100m"
---
apiVersion: v1
kind: Service
metadata:
  name: httpdoges
  namespace: httpdoges
spec:
  selector:
    app: httpdoges
  ports:
    - protocol: TCP
      port: 80
      targetPort: 80
  type: ClusterIP
--- 
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: httpdoges-home
  namespace: httpdoges
  annotations:
    nginx.ingress.kubernetes.io/use-proxy-protocol: "true"
    nginx.ingress.kubernetes.io/proxy-real-ip-cidr: "0.0.0.0/0"
    nginx.ingress.kubernetes.io/configuration-snippet: |
      proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
      proxy_set_header X-Real-IP $remote_addr;
spec:
  ingressClassName: nginx
  rules:
  - host: dogehttp.codes
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: httpdoges
            port:
              number: 80